name: Compile installer

on:
  schedule:
    - cron: '27 13 * * *'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get PocketMine-MP version
        id: pmmp_version
        run: |
          release=`curl -s https://api.github.com/repos/pmmp/PocketMine-MP/releases/latest`
          VERSION=`echo $release | jq -r '.tag_name'`
          CHANGELOG=`echo ${VERSION} | sed 's/\.[0-9]*//2'`.md#`echo ${VERSION} | sed 's/\.*//g'`

          echo $VERSION > version_cache

          store() { echo "::set-output name=$1::$2"; }
          store VERSION $VERSION
          store CHANGELOG $CHANGELOG

      - uses: actions/cache@v2
        id: cache
        with:
          path: version_cache
          key: pmmp-files-${{ steps.pmmp_version.outputs.VERSION }}

      - name: Rewrite install.nsi
        if: steps.cache.outputs.cache-hit != 'true'
        run: sed -i 's/0.0.0/${{ steps.pmmp_version.outputs.VERSION }}/' install.nsi

      - name: Download files
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -JLOs "https://github.com/pmmp/PHP-Binaries/releases/download/php-8.0-latest/PHP-Windows-x64-PM4.zip" &
          curl -JLOs "https://github.com/pmmp/PocketMine-MP/releases/download/${{ steps.pmmp_version.outputs.VERSION }}/PocketMine-MP.phar" &
          curl -JLOs "https://github.com/pmmp/PocketMine-MP/releases/download/${{ steps.pmmp_version.outputs.VERSION }}/start.cmd" &
          wait
          unzip -q PHP-8.0-Windows-x64-PM4.zip

      - name: Create installer
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update -qq && sudo apt-get install -qq -y nsis > /dev/null
          makensis install.nsi

      - name: Create Release
        if: steps.cache.outputs.cache-hit != 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.pmmp_version.outputs.VERSION }}
          release_name: PocketMine-MP ${{ steps.pmmp_version.outputs.VERSION }}
          body: |
            Release PocketMine-MP ${{ steps.pmmp_version.outputs.VERSION }}.
            You can see changelogs [here](https://github.com/pmmp/PocketMine-MP/blob/${{ steps.pmmp_version.outputs.VERSION }}/changelogs/${{ steps.pmmp_version.outputs.CHANGELOG }}).

      - name: Upload Release Asset
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PocketMine-MP-${{ steps.pmmp_version.outputs.VERSION }}.exe
          asset_name: PocketMine-MP-${{ steps.pmmp_version.outputs.VERSION }}.exe
          asset_content_type: application/octet-stream
